### ISSUE TITLE
No digiKam Album found for ... on Windows

### ISSUE THREAD

**Issue by Philipp91** [Philipp91/picasa2digikam#3]
Output:

```
c:\Programme_Manuell\_GRAFIK\picasa2digikam-main>python  .\main.py --dry_run --photos_dir "X:\Dokumente\Fotos 2011" --digikam_db="C:\Users\Martin\Pictures\digiKam\digikam4.db" -v
INFO: Inspecting existing digiKam database
INFO: serial_to_mountpoints={3133486939: {'C:\\'}, 3923689904: {'X:\\'}, 305419896: {'Y:\\'}}
INFO: album_roots={WindowsPath('C:/Users/Martin/Pictures/digiKam'): 1, WindowsPath('X:/Dokumente/Fotos 2011'): 2}
INFO: DigikamDb(file=WindowsPath('C:/Users/Martin/Pictures/digiKam/digikam4.db'), conn=<sqlite3.Connection object at 0x000002BA156EAD40>, album_roots={WindowsPath('C:/Users/Martin/Pictures/digiKam'): 1, WindowsPath('X:/Dokumente/Fotos 2011'): 2}, person_root_tag=4, internal_tags_id=1, pick_tags=[25, 24, 23, 22], star_tag=25)
INFO: Traversing input directories
INFO: ===========================================================================================
INFO: Now migrating X:\Dokumente\Fotos 2011\2011-01-01
INFO: Creating digiKam tag Picasa
INFO: Creating digiKam person tag XXX
INFO: ===========================================================================================
INFO: Now migrating X:\Dokumente\Fotos 2011\2011-01-02
INFO: Creating digiKam tag Picasa
INFO: Creating digiKam person tag XXX
INFO: Creating digiKam person tag XXX
INFO: ===========================================================================================
INFO: Now migrating X:\Dokumente\Fotos 2011\2011-01-02\HDR
Traceback (most recent call last):
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\main.py", line 57, in <module>
    main()
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\main.py", line 50, in main
    migrator.migrate_directories_under(input_root_dir=args.photos_dir, db=db, dry_run=args.dry_run)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\migrator.py", line 31, in migrate_directories_under
    contact_tags_per_dir[dir] = migrate_directory(dir, files, db, contact_tags_per_dir, dry_run=dry_run)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\migrator.py", line 47, in migrate_directory
    album_id = db.find_album_by_dir(input_dir)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\digikam_db.py", line 91, in find_album_by_dir
    raise ValueError('No digiKam Album found for %s (relative path %s) under root %s' % (path, relative_path, root_id))
ValueError: No digiKam Album found for X:\Dokumente\Fotos 2011\2011-01-02\HDR (relative path /2011-01-02\HDR) under root 2
```

_Originally posted by @Kuki77 in https://github.com/Philipp91/picasa2digikam/issues/1#issuecomment-1036032651_

**Comment by Kuki77** [comment]
Oh thanks for creating a second issue. I wasn't sure how to deal with it, as you're right, the #1 is solved (and also thanks for this!).

For rechecking it, I deleted (moved out) the HDR album) and tried again. But it seems the issue is every time if there are sub-sub-folders (see the different \ instead of /).

Here another try:
c:\Programme_Manuell\_GRAFIK\picasa2digikam-main>python  .\main.py --dry_run --photos_dir "X:\Dokumente\Fotos 2011" --digikam_db="C:\Users\Martin\Pictures\digiKam\digikam4.db" -v
INFO: Inspecting existing digiKam database
INFO: serial_to_mountpoints={3133486939: {'C:\\'}, 3923689904: {'X:\\'}, 305419896: {'Y:\\'}}
INFO: album_roots={WindowsPath('C:/Users/Martin/Pictures/digiKam'): 1, WindowsPath('X:/Dokumente/Fotos 2011'): 2}
INFO: DigikamDb(file=WindowsPath('C:/Users/Martin/Pictures/digiKam/digikam4.db'), conn=<sqlite3.Connection object at 0x0000021B410EAD40>, album_roots={WindowsPath('C:/Users/Martin/Pictures/digiKam'): 1, WindowsPath('X:/Dokumente/Fotos 2011'): 2}, person_root_tag=4, internal_tags_id=1, pick_tags=[25, 24, 23, 22], star_tag=25)
INFO: Traversing input directories
INFO: ===========================================================================================
INFO: Now migrating X:\Dokumente\Fotos 2011\2011-01-01
INFO: Creating digiKam tag Picasa
INFO: Creating digiKam person tag XXX
INFO: ===========================================================================================
INFO: Now migrating X:\Dokumente\Fotos 2011\2011-01-02
INFO: Creating digiKam tag Picasa
INFO: Creating digiKam person tag XXX
INFO: Creating digiKam person tag XXX
INFO: ===========================================================================================
INFO: Now migrating X:\Dokumente\Fotos 2011\2011-01-02_NewYear
INFO: Creating digiKam tag Picasa
INFO: Creating digiKam person tag XXX
WARNING: Unused INI sections in X:\Dokumente\Fotos 2011\2011-01-02_NewYear\.picasa.ini: {'DSC00217.ARW', 'DSC00188.ARW', 'DSC00199.ARW', 'DSC00192.ARW', 'DSC00193.ARW', 'DSC00185.ARW', 'DSC00184.ARW', 'DSC00197.ARW', 'DSC00201.ARW'}
INFO: ===========================================================================================
INFO: Now migrating X:\Dokumente\Fotos 2011\2011-01-02_NewYear\Edited
Traceback (most recent call last):
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\main.py", line 57, in <module>
    main()
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\main.py", line 50, in main
    migrator.migrate_directories_under(input_root_dir=args.photos_dir, db=db, dry_run=args.dry_run)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\migrator.py", line 31, in migrate_directories_under
    contact_tags_per_dir[dir] = migrate_directory(dir, files, db, contact_tags_per_dir, dry_run=dry_run)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\migrator.py", line 47, in migrate_directory
    album_id = db.find_album_by_dir(input_dir)
  File "c:\Programme_Manuell\_GRAFIK\picasa2digikam-main\digikam_db.py", line 91, in find_album_by_dir
    raise ValueError('No digiKam Album found for %s (relative path %s) under root %s' % (path, relative_path, root_id))
ValueError: No digiKam Album found for X:\Dokumente\Fotos 2011\2011-01-02_NewYear\Edited (relative path /2011-01-02_NewYear\Edited) under root 2

digiKam itself is dealing well with sub-subfolders:
https://snipboard.io/p80SOq.jpg

**Comment by Philipp91** [comment]
Please try the path in #4.
